=== manueldelapenna/contable/src/AfipBundle/Entity/etc/dataTypes/qFileHelper.config.dtd
<!ELEMENT config (defaultMimeType, mimeTypes)>

<!ELEMENT defaultMimeType EMPTY>
<!ATTLIST defaultMimeType id CDATA #REQUIRED>

<!ELEMENT mimeTypes (mimeType+)>

<!ELEMENT mimeType EMPTY>
<!ATTLIST mimeType extensions CDATA #REQUIRED>
<!ATTLIST mimeType type CDATA #REQUIRED>
<!ATTLIST mimeType id ID #REQUIRED>

=== manueldelapenna/contable/src/AppBundle/Entity/Afip/etc/dataTypes/qFileHelper.config.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE config SYSTEM "qFileHelper.config.dtd">
<config>
	<defaultMimeType id="i0692" />
	<mimeTypes>
		<mimeType id="i0001" type="application/andrew-inset" extensions="ez" />
		<mimeType id="i0002" type="application/applixware" extensions="aw" />
		<mimeType id="i0003" type="application/atom+xml" extensions="atom" />
		<mimeType id="i0004" type="application/atomcat+xml" extensions="atomcat" />
		<mimeType id="i0005" type="application/atomsvc+xml" extensions="atomsvc" />
		<mimeType id="i0006" type="application/ccxml+xml" extensions="ccxml" />
		<mimeType id="i0007" type="application/cdmi-capability" extensions="cdmia" />
		<mimeType id="i0008" type="application/cdmi-container" extensions="cdmic" />
		<mimeType id="i0009" type="application/cdmi-domain" extensions="cdmid" />
		<mimeType id="i0010" type="application/cdmi-object" extensions="cdmio" />
		<mimeType id="i0011" type="application/cdmi-queue" extensions="cdmiq" />
		<mimeType id="i0012" type="application/cu-seeme" extensions="cu" />
		<mimeType id="i0013" type="application/davmount+xml" extensions="davmount" />
		<mimeType id="i0014" type="application/docbook+xml" extensions="dbk" />
		<mimeType id="i0015" type="application/dssc+der" extensions="dssc" />
		<mimeType id="i0016" type="application/dssc+xml" extensions="xdssc" />
		<mimeType id="i0017" type="application/ecmascript" extensions="ecma" />
		<mimeType id="i0018" type="application/emma+xml" extensions="emma" />
		<mimeType id="i0019" type="application/epub+zip" extensions="epub" />
		<mimeType id="i0020" type="application/exi" extensions="exi" />
		<mimeType id="i0021" type="application/font-tdpfr" extensions="pfr" />
		<mimeType id="i0022" type="application/gml+xml" extensions="gml" />
		<mimeType id="i0023" type="application/gpx+xml" extensions="gpx" />
		<mimeType id="i0024" type="application/gxf" extensions="gxf" />
		<mimeType id="i0025" type="application/hyperstudio" extensions="stk" />
		<mimeType id="i0026" type="application/inkml+xml" extensions="ink|inkml" />
		<mimeType id="i0027" type="application/ipfix" extensions="ipfix" />
		<mimeType id="i0028" type="application/java-archive" extensions="jar" />
		<mimeType id="i0029" type="application/java-serialized-object" extensions="ser" />
		<mimeType id="i0030" type="application/java-vm" extensions="class" />
		<mimeType id="i0031" type="application/javascript" extensions="js" />
		<mimeType id="i0032" type="application/json" extensions="json" />
		<mimeType id="i0033" type="application/jsonml+json" extensions="jsonml" />
		<mimeType id="i0034" type="application/lost+xml" extensions="lostxml" />
		<mimeType id="i0035" type="application/mac-binhex40" extensions="hqx" />
		<mimeType id="i0036" type="application/mac-compactpro" extensions="cpt" />
		<mimeType id="i0037" type="application/mads+xml" extensions="mads" />
		<mimeType id="i0038" type="application/marc" extensions="mrc" />
		<mimeType id="i0039" type="application/marcxml+xml" extensions="mrcx" />
		<mimeType id="i0040" type="application/mathematica" extensions="ma|nb|mb" />
		<mimeType id="i0041" type="application/mathml+xml" extensions="mathml" />
		<mimeType id="i0042" type="application/mbox" extensions="mbox" />
		<mimeType id="i0043" type="application/mediaservercontrol+xml" extensions="mscml" />
		<mimeType id="i0044" type="application/metalink+xml" extensions="metalink" />
		<mimeType id="i0045" type="application/metalink4+xml" extensions="meta4" />
		<mimeType id="i0046" type="application/mets+xml" extensions="mets" />
		<mimeType id="i0047" type="application/mods+xml" extensions="mods" />
		<mimeType id="i0048" type="application/mp21" extensions="m21|mp21" />
		<mimeType id="i0049" type="application/mp4" extensions="mp4s" />
		<mimeType id="i0050" type="application/msword" extensions="doc|dot" />
		<mimeType id="i0051" type="application/mxf" extensions="mxf" />
		<mimeType id="i0052" type="application/octet-stream" extensions="bin|dms|lrf|mar|so|dist|distz|pkg|bpk|dump|elc|deploy" />
		<mimeType id="i0053" type="application/oda" extensions="oda" />
		<mimeType id="i0054" type="application/oebps-package+xml" extensions="opf" />
		<mimeType id="i0055" type="application/ogg" extensions="ogx" />
		<mimeType id="i0056" type="application/omdoc+xml" extensions="omdoc" />
		<mimeType id="i0057" type="application/onenote" extensions="onetoc|onetoc2|onetmp|onepkg" />
		<mimeType id="i0058" type="application/oxps" extensions="oxps" />
		<mimeType id="i0059" type="application/patch-ops-error+xml" extensions="xer" />
		<mimeType id="i0060" type="application/pdf" extensions="pdf" />
		<mimeType id="i0061" type="application/pgp-encrypted" extensions="pgp" />
		<mimeType id="i0062" type="application/pgp-signature" extensions="asc|sig" />
		<mimeType id="i0063" type="application/pics-rules" extensions="prf" />
		<mimeType id="i0064" type="application/pkcs10" extensions="p10" />
		<mimeType id="i0065" type="application/pkcs7-mime" extensions="p7m|p7c" />
		<mimeType id="i0066" type="application/pkcs7-signature" extensions="p7s" />
		<mimeType id="i0067" type="application/pkcs8" extensions="p8" />
		<mimeType id="i0068" type="application/pkix-attr-cert" extensions="ac" />
		<mimeType id="i0069" type="application/pkix-cert" extensions="cer" />
		<mimeType id="i0070" type="application/pkix-crl" extensions="crl" />
		<mimeType id="i0071" type="application/pkix-pkipath" extensions="pkipath" />
		<mimeType id="i0072" type="application/pkixcmp" extensions="pki" />
		<mimeType id="i0073" type="application/pls+xml" extensions="pls" />
		<mimeType id="i0074" type="application/postscript" extensions="ai|eps|ps" />
		<mimeType id="i0075" type="application/prs.cww" extensions="cww" />
		<mimeType id="i0076" type="application/pskc+xml" extensions="pskcxml" />
		<mimeType id="i0077" type="application/rdf+xml" extensions="rdf" />
		<mimeType id="i0078" type="application/reginfo+xml" extensions="rif" />
		<mimeType id="i0079" type="application/relax-ng-compact-syntax" extensions="rnc" />
		<mimeType id="i0080" type="application/resource-lists+xml" extensions="rl" />
		<mimeType id="i0081" type="application/resource-lists-diff+xml" extensions="rld" />
		<mimeType id="i0082" type="application/rls-services+xml" extensions="rs" />
		<mimeType id="i0083" type="application/rpki-ghostbusters" extensions="gbr" />
		<mimeType id="i0084" type="application/rpki-manifest" extensions="mft" />
		<mimeType id="i0085" type="application/rpki-roa" extensions="roa" />
		<mimeType id="i0086" type="application/rsd+xml" extensions="rsd" />
		<mimeType id="i0087" type="application/rss+xml" extensions="rss" />
		<mimeType id="i0088" type="application/rtf" extensions="rtf" />
		<mimeType id="i0089" type="application/sbml+xml" extensions="sbml" />
		<mimeType id="i0090" type="application/scvp-cv-request" extensions="scq" />
		<mimeType id="i0091" type="application/scvp-cv-response" extensions="scs" />
		<mimeType id="i0092" type="application/scvp-vp-request" extensions="spq" />
		<mimeType id="i0093" type="application/scvp-vp-response" extensions="spp" />
		<mimeType id="i0094" type="application/sdp" extensions="sdp" />
		<mimeType id="i0095" type="application/set-payment-initiation" extensions="setpay" />
		<mimeType id="i0096" type="application/set-registration-initiation" extensions="setreg" />
		<mimeType id="i0097" type="application/shf+xml" extensions="shf" />
		<mimeType id="i0098" type="application/smil+xml" extensions="smi|smil" />
		<mimeType id="i0099" type="application/sparql-query" extensions="rq" />
		<mimeType id="i0100" type="application/sparql-results+xml" extensions="srx" />
		<mimeType id="i0101" type="application/srgs" extensions="gram" />
		<mimeType id="i0102" type="application/srgs+xml" extensions="grxml" />
		<mimeType id="i0103" type="application/sru+xml" extensions="sru" />
		<mimeType id="i0104" type="application/ssdl+xml" extensions="ssdl" />
		<mimeType id="i0105" type="application/ssml+xml" extensions="ssml" />
		<mimeType id="i0106" type="application/tei+xml" extensions="tei|teicorpus" />
		<mimeType id="i0107" type="application/thraud+xml" extensions="tfi" />
		<mimeType id="i0108" type="application/timestamped-data" extensions="tsd" />
		<mimeType id="i0109" type="application/vnd.3gpp.pic-bw-large" extensions="plb" />
		<mimeType id="i0110" type="application/vnd.3gpp.pic-bw-small" extensions="psb" />
		<mimeType id="i0111" type="application/vnd.3gpp.pic-bw-var" extensions="pvb" />
		<mimeType id="i0112" type="application/vnd.3gpp2.tcap" extensions="tcap" />
		<mimeType id="i0113" type="application/vnd.3m.post-it-notes" extensions="pwn" />
		<mimeType id="i0114" type="application/vnd.accpac.simply.aso" extensions="aso" />
		<mimeType id="i0115" type="application/vnd.accpac.simply.imp" extensions="imp" />
		<mimeType id="i0116" type="application/vnd.acucobol" extensions="acu" />
		<mimeType id="i0117" type="application/vnd.acucorp" extensions="atc|acutc" />
		<mimeType id="i0118" type="application/vnd.adobe.air-application-installer-package+zip" extensions="air" />
		<mimeType id="i0119" type="application/vnd.adobe.formscentral.fcdt" extensions="fcdt" />
		<mimeType id="i0120" type="application/vnd.adobe.fxp" extensions="fxp|fxpl" />
		<mimeType id="i0121" type="application/vnd.adobe.xdp+xml" extensions="xdp" />
		<mimeType id="i0122" type="application/vnd.adobe.xfdf" extensions="xfdf" />
		<mimeType id="i0123" type="application/vnd.ahead.space" extensions="ahead" />
		<mimeType id="i0124" type="application/vnd.airzip.filesecure.azf" extensions="azf" />
		<mimeType id="i0125" type="application/vnd.airzip.filesecure.azs" extensions="azs" />
		<mimeType id="i0126" type="application/vnd.amazon.ebook" extensions="azw" />
		<mimeType id="i0127" type="application/vnd.americandynamics.acc" extensions="acc" />
